apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curriculum
spec:
  template:
    spec:
      selector:
        - app: curriculum
      containers:
        - name: akamongo
          image: mongo
          ports:
          - containerPort: 27017
        - name: akaserver
          image: gcr.io/labcluster-1264/curriculum-server:v1
          ports:
          - containerPort: 8080
        - name: akabeanstalk
          image: gcr.io/labcluster-1264/curriculum-beanstalk:v1
          ports:
          - containerPort: 14711
        - name: akaworker
          image: gcr.io/labcluster-1264/curriculum-worker:v2

  
