apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curriculum
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: curriculum
    spec:
      containers:
      - name: akamongo
        image: mongo
        ports:
        - containerPort: 27017
      - name: akaserver
        image: gcr.io/nyt-rnd/curriculum-server:v2
        ports:
        - containerPort: 8080
      - name: akabeanstalk
        image: gcr.io/nyt-rnd/curriculum-beanstalk:v1
        ports:
        - containerPort: 14711
      - name: akaworker
        image: gcr.io/nyt-rnd/curriculum-worker:v1

  
